export const QUESTIONS = [
  "What makes the Mona Lisa's smile so enigmatic?",
  "Why do zebras have stripes?",
  "What is the origin of the tradition of blowing out birthday candles?",
  "Why does time seem to slow down when we're afraid?",
  "What's the science behind the browning of apples?",
  "What causes a mirage to appear in the desert?",
  "How did the tradition of April Fool's Day start?",
  "Why do we get goosebumps when we're scared or cold?",
  "What's the history behind the superstition of Friday the 13th?",
  "Why do we see certain colors when we rub our eyes?",
  "How do chameleons change their color?",
  "What's the story behind the invention of the chocolate chip cookie?",
  "What causes the Northern and Southern Lights?",
  "Why do certain foods taste different when they're cold versus hot?",
  "How does echolocation work in bats and dolphins?",
  "What causes people to have different types of fingerprints?",
  "What's the history behind the creation of the first computer?",
  "Why do onions make us cry?",
  "What's the significance of the dreamcatcher in Native American culture?",
  "What's the science behind why we find puppies cute?",
  "What are the theories behind the construction of the Pyramids of Giza?",
  "How does the Venus flytrap know when to close its trap?",
  "What's the story behind the invention of Post-It Notes?",
  "Why does the sound of fingernails on a chalkboard make us cringe?",
  "What's the history of the discovery of dinosaurs?",
  "Why do we feel dizzy when we spin?",
  "What's the science behind why we find certain jokes funny?",
  "Why do flamingos stand on one leg?",
  "What's the story behind the creation of the first crossword puzzle?",
  "How does a firefly produce light?",
  "Why do we see stars when we sneeze?",
  "What is the origin and purpose of the Nobel Prize?",
  "Why are most barns painted red?",
  "How does a spider spin a web?",
  "What is the Fibonacci sequence and where can it be seen in nature?",
  'Why do we "see stars" after a sudden blow to the head?',
  "What is the role of the queen bee in a hive?",
  "Why do some birds migrate and how do they navigate?",
  "What's the history of the invention of the light bulb?",
  "Why does the moon appear larger near the horizon?",
  "How do Venus flytraps know when to snap shut?",
  "What's the science behind why popcorn pops?",
  "Why does our voice sound different to us than to others?",
  "What's the origin of the tradition of shaking hands?",
  "How does our body create and store memories?",
];
